# ================================
# PostgreSQL (SOURCE DB)
# ================================
spring.datasource.source.jdbc-url=jdbc:postgresql://UAT-IP:5432/smms_db
spring.datasource.source.username=postgres
spring.datasource.source.password=uatpassword
spring.datasource.source.driver-class-name=org.postgresql.Driver

# ================================
# Oracle (TARGET DB)
# ================================
spring.datasource.target.jdbc-url=jdbc:oracle:thin:@//UAT-IP:1521/XEPDB1
spring.datasource.target.username=suraksha
spring.datasource.target.password=uatpassword
spring.datasource.target.driver-class-name=oracle.jdbc.OracleDriver
