# ================================
# PostgreSQL (SOURCE DB)
# ================================
spring.datasource.source.jdbc-url=jdbc:postgresql://10.00.00.90:5432/postgres
spring.datasource.source.username=postgres
spring.datasource.source.password=postgres
spring.datasource.source.driver-class-name=org.postgresql.Driver

# ================================
# Oracle (TARGET DB)
# ================================
spring.datasource.target.jdbc-url=jdbc:oracle:thin:@//10.00.4.100:1521/SMMSDB
spring.datasource.target.username=SURAKSHA
spring.datasource.target.password=Suraksha
spring.datasource.target.driver-class-name=oracle.jdbc.OracleDriver



