# ================================
# PostgreSQL (SOURCE DB)
# ================================
spring.datasource.source.jdbc-url=jdbc:postgresql://10.77.52.72:5432/postgres
spring.datasource.source.username=postgres
spring.datasource.source.password=postgres3
spring.datasource.source.driver-class-name=org.postgresql.Driver

# ================================
# Oracle (TARGET DB)
# ================================
spring.datasource.target.jdbc-url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.target.username=suraksha
spring.datasource.target.password=password
spring.datasource.target.driver-class-name=oracle.jdbc.OracleDriver
